### ISSUE TITLE
parametrize LLM backend

### ISSUE THREAD

**Issue by meirm** [rahulnyk/fountain-pen#22]
Add OPENAI_MODEL, OPENAI_BASE_URL so it is possible to use other models beside gpt-3.5-turbo and use LMStudio or other server.
I tried to replace the hard coded 'gpt-3.5-turbo' instances to use process.env.OPENAI_MODEL but failed to compile.

**Comment by rahulnyk** [comment]
This is a good enhancement. 
Ill try to build this up, but may take sometime.

**Comment by meirm** [comment]
Thanks, mission accomplished.
