### ISSUE TITLE
Can't read Faiss.index

### ISSUE THREAD

**Issue by meirm** [rahulnyk/fountain-pen#28]
<img width="726" alt="Screenshot 2024-07-25 at 20 21 39" src="https://github.com/user-attachments/assets/e19123ef-fbc9-4527-bfb8-b513d3fd8855">
<img width="748" alt="Screenshot 2024-07-25 at 20 20 59" src="https://github.com/user-attachments/assets/44d4de30-a6ec-42c4-b14a-51b074bb0c9b">

**Comment by meirm** [comment]
I was able to circumvent this issue as you will see on my next pull request where I added all the changes to allow me to use LMStudio with local LLMs instead of OpenAI services.

**Comment by rahulnyk** [comment]
I am working on this may take a few days though.

**Comment by meirm** [comment]
Did you see my related pull request?

**Comment by rahulnyk** [comment]
yes. Thanks for adding this feature :) 
I am yet to reconcile it though. 
give me a day or two

**Comment by meirm** [comment]
Fixed
